insert into teams set location = 'Arizona', team_name = 'Cardinals';
insert into teams set location = 'Atlanta', team_name = 'Falcons';
insert into teams set location = 'Baltimore', team_name = 'Ravens';
insert into teams set location = 'Buffalo', team_name = 'Bills';
insert into teams set location = 'Carolina', team_name = 'Panthers';
insert into teams set location = 'Chicago', team_name = 'Bears';
insert into teams set location = 'Cincinnati', team_name = 'Bengals';
insert into teams set location = 'Cleveland', team_name = 'Browns';
insert into teams set location = 'Dallas', team_name = 'Cowboys';
insert into teams set location = 'Denver', team_name = 'Broncos';
insert into teams set location = 'Detroit', team_name = 'Lions';
insert into teams set location = 'Green Bay', team_name = 'Packers';
insert into teams set location = 'Houston', team_name = 'Texans';
insert into teams set location = 'Indianapolis', team_name = 'Colts';
insert into teams set location = 'Jacksonville', team_name = 'Jaguars';
insert into teams set location = 'Kansas City', team_name = 'Chiefs';
insert into teams set location = 'Las Vegas', team_name = 'Raiders';
insert into teams set location = 'Los Angeles', team_name = 'Chargers';
insert into teams set location = 'Los Angeles', team_name = 'Rams';
insert into teams set location = 'Miami', team_name = 'Dolphins';
insert into teams set location = 'Minnesota', team_name = 'Vikings';
insert into teams set location = 'New England', team_name = 'Patriots';
insert into teams set location = 'New Orleans', team_name = 'Saints';
insert into teams set location = 'New York', team_name = 'Giants';
insert into teams set location = 'New York', team_name = 'Jets';
insert into teams set location = 'Philadelphia', team_name = 'Eagles';
insert into teams set location = 'Pittsburgh', team_name = 'Steelers';
insert into teams set location = 'San Francisco', team_name = '49ers';
insert into teams set location = 'Seattle', team_name = 'Seahawks';
insert into teams set location = 'Tampa Bay', team_name = 'Buccaneers';
insert into teams set location = 'Tennessee', team_name = 'Titans';
insert into teams set location = 'Washington', team_name = 'Commanders';